### ISSUE TITLE
Install Fails (ncurses missing)

### ISSUE THREAD

**Issue by rtfmoz** [robsalasco/homebrew-profanity#12]
https://gist.github.com/rtfmoz/fcb2a9b30ad9762123e6

**Comment by rtfmoz** [comment]
Seems the latest version of mac osx comes with ncurses so the dependancy is not required. I did a brew edit profanity and commented out the line #       depend_on 'ncurses'

Then brew install profanity --HEAD worked as expected.

In homebrew, ncurses is now listed under the homebrew-dupes as it duplicates built in functionality of mac osx. You can force it to install with brew tap homebrew/dupes; brew install ncurses; brew ln --force ncurses. But then brew doctor warns you that its overriding system libraries. So I removed it.

**Comment by MSylvia** [comment]
Thanks :)
`brew edit profanity` and commenting out `# depend_on 'ncurses'` worked for me as well.
Confirmed on OSX 10.8.4

**Comment by robsalasco** [comment]
Confirmed!
